### ISSUE TITLE
API key commited

### ISSUE THREAD

**Issue by AdamSlack** [NTUDevSoc/SlackBot#2]
Just wondering if the API key was committed intentionally?

**Comment by HattMarris1** [comment]
probably shouldn't be, @deanott I think this is in the bit you wrote of the catbot script?

**Comment by AdamSlack** [comment]
Was just poking around, though I'd say something in case you wanted it secret :+1:

**Comment by HattMarris1** [comment]
cheers for pointing it out

**Comment by HattMarris1** [comment]
Right, I think it's been removed completely from the repo and replaced with an environment variable
